# Generated by Django 4.1.13 on 2026-02-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pemasok', models.CharField(max_length=50, unique=True)),
                ('nama_supplier', models.CharField(max_length=150)),
                ('kontak', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
