# Generated by Django 4.1.13 on 2026-02-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelolaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_input', models.DateField()),
                ('tanggal', models.DateField()),
                ('jenis_beras', models.CharField(max_length=100)),
                ('kuantitas_kg', models.IntegerField()),
                ('stok_kg', models.IntegerField()),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier')),
            ],
        ),
    ]
