# Generated by Django 4.1.13 on 2026-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_keloladata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keloladata',
            name='tanggal_input',
        ),
        migrations.AlterField(
            model_name='keloladata',
            name='harga_per_kg',
            field=models.IntegerField(),
        ),
    ]
