# Generated by Django 4.1.13 on 2026-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_keloladata_tanggal_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_beras', models.CharField(max_length=100)),
                ('stok_target', models.FloatField()),
                ('kuantitas_target', models.FloatField()),
                ('harga_prediksi', models.FloatField()),
                ('nilai_rmse', models.FloatField()),
                ('k_digunakan', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
