# Generated by Django 4.1.13 on 2026-02-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_hasilprediksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilprediksi',
            name='detail_perhitungan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
