# Generated by Django 6.0.5 on 2026-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_hasilprediksi_detail_perhitungan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilprediksi',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='hasilprediksi',
            constraint=models.UniqueConstraint(fields=('tanggal',), name='unique_hasil_prediksi_per_tanggal'),
        ),
    ]
